name: zone
description: Yet another HackerNews client.
publish_to: 'none'

version: 0.2.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  url_launcher: ^6.1.10
  share_plus: ^6.3.1
  json_annotation: ^4.8.0
  path_provider: ^2.0.14
  flutter_riverpod: ^2.3.2
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  google_mobile_ads: ^2.4.0
  shimmer: ^2.0.0
  flutter_widget_from_html: ^0.10.0
  cached_network_image: ^3.2.3
  webview_flutter: ^4.0.7
  flutter_native_splash: ^2.2.19
  syncfusion_flutter_pdfviewer: ^21.1.37

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png

flutter_native_splash:
  color: "#20272B"
  image: assets/images/splash.png
