name: zone
description: A Hacker News client.
publish_to: 'none'
version: 0.1.1

## Slidy Scripts
vars:
  clean: flutter clean
  get: flutter pub get
  run: flutter pub run
  runner: flutter pub run build_runner
  build: flutter build
scripts:
  build: $runner build --delete-conflicting-outputs
  watch: $runner watch
  icon: $run flutter_launcher_icons:main
  apk: $get & $runner build --delete-conflicting-outputs & $build apk --split-per-abi
  appbundle: $get & $runner build --delete-conflicting-outputs & $build appbundle
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  flutter_modular: ^2.0.1
  material_design_icons_flutter: ^4.0.5855
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  url_launcher: ^5.7.10
  fluttertoast: ^7.1.6
  share: ^0.6.5+4
  incrementally_loading_listview: ^0.3.0
  flutter_inappwebview: ^4.0.0+4
  flutter_html: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  json_annotation: ^3.1.1
  flutter_slidable: ^0.5.7
  path_provider: ^1.6.27
  intl: ^0.16.1
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  effective_dart: ^1.3.0
  mockito: ^4.1.3
  modular_codegen: ^2.0.1
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.13
  flutter_launcher_icons: ^0.8.1
  hive_generator: ^0.8.2

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
